stages:
- name: Copy secrets
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: |
        cd bin
        chmod +x ./env-populate
        ./env-populate
        cd .. && cp .env.prod .env
    envFrom:
    - sourceName: tbd-pipeline
      sourceKey: CANONICAL_URL
      targetKey: CANONICAL_URL
    - sourceName: tbd-pipeline
      sourceKey: SESSION_SECRET
      targetKey: SESSION_SECRET
    - sourceName: tbd-pipeline
      sourceKey: SESSION_MAX_AGE_MS
      targetKey: SESSION_MAX_AGE_MS
    - sourceName: tbd-pipeline
      sourceKey: BUILD_GRAPHQL_URL
      targetKey: BUILD_GRAPHQL_URL
    - sourceName: tbd-pipeline
      sourceKey: ENABLE_SPA_ROUTING
      targetKey: ENABLE_SPA_ROUTING
    - sourceName: tobedressed
      sourceKey: EXTERNAL_GRAPHQL_URL
      targetKey: EXTERNAL_GRAPHQL_URL
    - sourceName: tbd-pipeline
      sourceKey: INTERNAL_GRAPHQL_URL
      targetKey: INTERNAL_GRAPHQL_URL
    - sourceName: tbd-pipeline
      sourceKey: SEGMENT_ANALYTICS_SKIP_MINIMIZE
      targetKey: SEGMENT_ANALYTICS_SKIP_MINIMIZE
    - sourceName: tbd-pipeline
      sourceKey: SEGMENT_ANALYTICS_WRITE_KEY
      targetKey: SEGMENT_ANALYTICS_WRITE_KEY
    - sourceName: tbd-pipeline
      sourceKey: PORT
      targetKey: PORT
    - sourceName: tbd-pipeline
      sourceKey: NEXT_BUILD_SEGMENT_ANALYTICS_WRITE_KEY
      targetKey: NEXT_PUBLIC_SEGMENT_ANALYTICS_WRITE_KEY
    - sourceName: tbd-pipeline
      sourceKey: NEXT_BUILD_SEGMENT_ANALYTICS_SKIP_MINIMIZE
      targetKey: NEXT_PUBLIC_SEGMENT_ANALYTICS_SKIP_MINIMIZE
    - sourceName: tbd-pipeline
      sourceKey: STRIPE_PUBLIC_API_KEY
      targetKey: STRIPE_PUBLIC_API_KEY
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: demandcluster/${CICD_GIT_REPO_NAME}:v4.1.0
      pushRemote: true
      registry: harbor.demandcluster.com
timeout: 60
branch: {}
notification: {}
